/*
 * Configuration Header File
 * Compile-time constants and parameters
 */

#ifndef CONFIG_H
#define CONFIG_H

// ==============================================================================
// COMPILE-TIME DEFAULTS (Easily configurable for recompilation)
// ==============================================================================

// Maximum wait period between Producer writes (seconds)
#define DEFAULT_MAX_PRODUCER_WAIT 2

// Maximum wait period between Consumer reads (seconds)
#define DEFAULT_MAX_CONSUMER_WAIT 4

// Maximum number of Producers supported
#define MAX_PRODUCERS 10

// Maximum number of Consumers supported
#define MAX_CONSUMERS 5

// Range of random numbers generated by Producer
#define RANDOM_VALUE_MIN 0
#define RANDOM_VALUE_MAX 9

// ==============================================================================
// PRIORITY LEVELS
// ==============================================================================

#define PRIORITY_LOW 0
#define PRIORITY_NORMAL 5
#define PRIORITY_HIGH 9

// ==============================================================================
// DEBUG AND INSTRUMENTATION
// ==============================================================================

// Debug mode: Set to 1 to enable detailed logging, 0 to disable
// When enabled, prints detailed information about queue operations,
// thread activities, and internal state changes
#define DEBUG_MODE 0

// ==============================================================================
// SYSTEM LIMITS
// ==============================================================================

// Maximum queue size allowed
#define MAX_QUEUE_SIZE 20

// Minimum queue size allowed
#define MIN_QUEUE_SIZE 1

#endif
